# Generated by Django 3.2 on 2021-04-22 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_image'),
        ('users', '0003_auto_20210421_2228'),
    ]

    operations = [
    ]
