# Generated by Django 3.2 on 2021-04-22 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_merge_20210422_0032'),
        ('users', '0005_alter_profile_user'),
    ]

    operations = [
    ]
