# Generated by Django 3.1.7 on 2021-04-24 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210423_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(default='CUSTOMER', max_length=20),
        ),
    ]
