# Generated by Django 3.1.7 on 2021-04-21 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210421_2237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='img_src',
            new_name='img',
        ),
    ]
