# Generated by Django 3.2 on 2021-04-22 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210421_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='product_imgs/'),
        ),
    ]
