# Generated by Django 3.2 on 2021-04-23 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_product_seller'),
        ('core', '0007_auto_20210423_1934'),
    ]

    operations = [
    ]
