# Generated by Django 3.1.7 on 2021-04-24 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210424_1038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='tags',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='tag',
        ),
    ]
