# Generated by Django 3.1.7 on 2021-04-24 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20210424_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='tags',
            field=models.CharField(choices=[('veg', 'Vegetables'), ('fruit', 'Fruits'), ('groc', 'Groceries')], max_length=20),
        ),
    ]
