# Generated by Django 3.1.7 on 2021-04-24 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210424_1042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tag',
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.CharField(choices=[('veg', 'Vegetables'), ('fruit', 'Fruits'), ('groc', 'Groceries')], default='veg', max_length=20),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
