# Generated by Django 3.1.7 on 2021-04-24 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20210424_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='measurment_unit',
            field=models.CharField(choices=[('kg', 'Kilograms'), ('lb', 'Pounds (lb)'), ('l', 'Litres'), ('no', 'Number (Individual pieces)'), ('bags', 'Bags')], default='kg', max_length=5),
        ),
    ]
