# Generated by Django 3.1.7 on 2021-04-24 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20210424_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.CharField(choices=[('vegetables', 'Vegetables'), ('fruits', 'Fruits'), ('groceries', 'Groceries')], default='vegetables', max_length=20),
        ),
    ]
