# Generated by Django 3.2 on 2021-04-24 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20210424_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.FileField(blank=True, default='default.png', null=True, upload_to='product_imgs/'),
        ),
    ]
