# Generated by Django 3.1.7 on 2021-04-24 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20210424_1805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='address1',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='address2',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='address',
            field=models.TextField(default='  '),
            preserve_default=False,
        ),
    ]
