# Generated by Django 3.2 on 2021-04-24 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_merge_0017_alter_product_img_0018_auto_20210424_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.FileField(blank=True, default='default.png', null=True, upload_to=''),
        ),
    ]
