# Generated by Django 3.1.7 on 2021-04-24 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_product_img'),
        ('core', '0020_auto_20210424_1903'),
    ]

    operations = [
    ]
