# Generated by Django 3.1.7 on 2021-04-24 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_merge_20210424_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='placed',
            field=models.BooleanField(default=False),
        ),
    ]
