# Generated by Django 3.1.7 on 2021-04-25 02:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20210425_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='stars',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
    ]
